export const foodList = [
    {
      name: "Oatmeal",
      protein: 12,
      fats: 6.5,
      carbs: 60,
      period: "breakfast",
      contraindications: [],
    },
    {
      name: "Chicken Breast",
      protein: 31,
      fats: 3.6,
      carbs: 0,
      period: "lunch",
      contraindications: [],
    },
    {
      name: "Eggs",
      protein: 13,
      fats: 11,
      carbs: 1,
      period: "breakfast",
      contraindications: ["cholesterol issues"],
    },
    {
      name: "Greek Yogurt (Low-fat)",
      protein: 10,
      fats: 0.4,
      carbs: 6,
      period: "snack",
      contraindications: ["dairy"],
    },
    {
      name: "Whole Wheat Bread",
      protein: 4,
      fats: 1,
      carbs: 20,
      period: "breakfast",
      contraindications: ["gluten"],
    },
    {
      name: "Avocado Toast",
      protein: 5,
      fats: 15,
      carbs: 20,
      period: "breakfast",
      contraindications: [],
    },
    {
      name: "Grilled Salmon",
      protein: 20,
      fats: 10,
      carbs: 0,
      period: "dinner",
      contraindications: ["fish"],
    },
    {
      name: "Brown Rice",
      protein: 2.6,
      fats: 0.9,
      carbs: 23,
      period: "lunch",
      contraindications: [],
    },
    {
      name: "Lentil Soup",
      protein: 9,
      fats: 0.4,
      carbs: 20,
      period: "lunch",
      contraindications: [],
    },
    {
      name: "Banana",
      protein: 1,
      fats: 0.3,
      carbs: 22,
      period: "snack",
      contraindications: [],
    },
    {
      name: "Mixed Nuts (Almonds, Walnuts)",
      protein: 20,
      fats: 50,
      carbs: 20,
      period: "snack",
      contraindications: ["nuts"],
    },
    {
      name: "Spinach Salad",
      protein: 2.9,
      fats: 0.4,
      carbs: 3.6,
      period: "lunch",
      contraindications: [],
    },
    {
      name: "Quinoa",
      protein: 14,
      fats: 6,
      carbs: 64,
      period: "lunch",
      contraindications: ["gluten intolerance"],
    },
    {
      name: "Tomato",
      protein: 1,
      fats: 0.2,
      carbs: 4,
      period: "lunch",
      contraindications: [],
    },
    {
      name: "Skim Milk",
      protein: 3.3,
      fats: 1.0,
      carbs: 4.8,
      period: "snack",
      contraindications: ["dairy"],
    },
    {
      name: "Cottage Cheese",
      protein: 10,
      fats: 4,
      carbs: 3,
      period: "snack",
      contraindications: ["dairy"],
    },
    {
      name: "Roasted Sweet Potatoes",
      protein: 2,
      fats: 0.1,
      carbs: 24,
      period: "lunch",
      contraindications: [],
    },
    {
      name: "Tuna Sandwich",
      protein: 20,
      fats: 8,
      carbs: 25,
      period: "lunch",
      contraindications: ["fish", "gluten"],
    },
    {
      name: "Boiled Eggs",
      protein: 13,
      fats: 11,
      carbs: 1,
      period: "breakfast",
      contraindications: [],
    },
    {
      name: "Apple",
      protein: 0.3,
      fats: 0.2,
      carbs: 25,
      period: "snack",
      contraindications: [],
    },
    {
      name: "Carrot Sticks",
      protein: 1,
      fats: 0.1,
      carbs: 9,
      period: "snack",
      contraindications: [],
    },
    {
      name: "Cucumber Salad",
      protein: 1,
      fats: 0.2,
      carbs: 4,
      period: "dinner",
      contraindications: [],
    },
    {
      name: "Baked Potato",
      protein: 3,
      fats: 0.1,
      carbs: 37,
      period: "dinner",
      contraindications: [],
    },
    {
      name: "Roasted Chicken Drumsticks",
      protein: 19,
      fats: 11,
      carbs: 0,
      period: "dinner",
      contraindications: [],
    },
  ];
  